In [1]:
import numpy as np
import pandas as pd

dataset= pd.read_csv('Data.csv')

In [2]:
X= dataset.iloc[:,:-1].values
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [4]:
y= dataset.iloc[:,-1].values
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [7]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=0)

In [9]:
from sklearn.linear_model import LinearRegression
MLR= LinearRegression()
model= MLR.fit(X_train,y_train)

In [12]:
y_pred = model.predict(X_test)

In [13]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9325315554761303